In [1]:
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5ODc2OTQyMiwianRpIjoiMDY5ZWRiMGMtNTUyMS00OWNkLWI5NjMtOTBiMzMyMTkyMGExIiwidHlwZSI6ImFjY2VzcyIsImlkZW50aXR5Ijp7ImlkIjozODUwOTYsInVzZXJuYW1lIjoiZHl1bWFuaTIzIn0sIm5iZiI6MTY5ODc2OTQyMiwiZXhwIjoxNzAyNjU3NDIyfQ.8gTAsJy5Emr_L9voK28AOMPKYPXdqnY0kzizauNuRok')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [2]:
import torch

# Tensors
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-dimensional array
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.]]
])

t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [8]:
t1.shape #Because it sia not an array

torch.Size([])

In [9]:
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


It is not possible to create tensors with an improper shape

## Tensor Operations and gradients

In [10]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [11]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

To caculate the gradient descent we have to calculate the derivative.
To calculate the derivative of y we can invoke .backward method

In [12]:
# Compute the derivative
y.backward()

THe derivative of the y is stored in the .grad property of the respective tensors

In [13]:
# Display gradients
print('dy/dx', x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


Note: x.grad is None because x doesn't have a require_grad set to True as we are not interested in the derivative of the x.

This is optimization as well as we do not want to calculate the derivative of every variable

## Tensor Functions

Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors.

In [14]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [15]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [16]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

# Interoperability with Numpy
Numpy is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

Matplotlib for plotting and visualization
OpenCV for image and video processing
Pandas for file I/O and data analysis
Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [17]:
import numpy as np

x = np.array([[1,2],
              [3,4]])
x

array([[1, 2],
       [3, 4]])

In [18]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [19]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

# Save the notebook

In [20]:
!pip install jovian --upgrade

In [22]:
jovian.commit()

[jovian] Detected Colab notebook...


[jovian] Error: Please provide the project argument for the first commit e.g. jovian.commit(project='my-project')


In [23]:
jovian.commit(project='01-pytorch-basics')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: ignored