In [1]:
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5ODc2OTQyMiwianRpIjoiMDY5ZWRiMGMtNTUyMS00OWNkLWI5NjMtOTBiMzMyMTkyMGExIiwidHlwZSI6ImFjY2VzcyIsImlkZW50aXR5Ijp7ImlkIjozODUwOTYsInVzZXJuYW1lIjoiZHl1bWFuaTIzIn0sIm5iZiI6MTY5ODc2OTQyMiwiZXhwIjoxNzAyNjU3NDIyfQ.8gTAsJy5Emr_L9voK28AOMPKYPXdqnY0kzizauNuRok')

# Gradient Descent and Linear regression with Pytorch

In [2]:
import numpy as np
import torch

## Training data
We can represent the training data using two matrices: inputs and targets, each with one row per observation, and one column per variable.

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [4]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

We've separated the input and target variables because we'll operate on them separately. Also, we've created numpy arrays, because this is typically how you would work with training data: read some CSV files as numpy arrays, do some processing, and then convert them to PyTorch tensors.

Let's convert the arrays to PyTorch tensors.

In [5]:
# Convert inputs and targets to Tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression model from scratch
The weights and biases (w11, w12,... w23, b1 & b2) can also be represented as matrices, initialized as random values. The first row of w and the first element of b are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [6]:
# Weights and biases randomly generated
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.9901, -0.3247, -0.9835],
        [-0.1272,  1.0764,  0.5628]], requires_grad=True)
tensor([-0.7388,  0.7784], requires_grad=True)


torch.randn creates a tensor with the given shape, with elements picked randomly from a normal distribution with mean 0 and standard deviation 1.

Our model is simply a function that performs a matrix multiplication of the inputs and the weights w (transposed) and adds the bias b (replicated for each observation).

matrix-mult

We can define the model as follows:

In [7]:
 inputs @ w.t() + b

tensor([[-137.0595,   87.8117],
        [-182.3533,  119.9456],
        [-187.4266,  166.5933],
        [-152.0782,   54.9106],
        [-169.0704,  134.7332]], grad_fn=<AddBackward0>)

In [8]:
def model(x):
  return x @ w.t() + b

In [9]:
# GEnerate Functions
preds = model(inputs)
print(preds)

tensor([[-137.0595,   87.8117],
        [-182.3533,  119.9456],
        [-187.4266,  166.5933],
        [-152.0782,   54.9106],
        [-169.0704,  134.7332]], grad_fn=<AddBackward0>)


In [10]:
# Compare the targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


You can see a big difference between our model's predictions and the actual targets because we've initialized our model with random weights and biases. Obviously, we can't expect a randomly initialized model to *just work*.

## Loss function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [11]:
# MSE loss
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of all the elements in a tensor. The `.numel` method of a tensor returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [12]:
# Compute the loss
loss = mse(targets, preds)
print(loss)

tensor(30722.2773, grad_fn=<DivBackward0>)


Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by the square root of the loss*. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. The result is called the *loss* because it indicates how bad the model is at predicting the target variables. It represents information loss in the model: the lower the loss, the better the model.

## Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases because they have `requires_grad` set to `True`. We'll see how this is useful in just a moment.

In [13]:
# Compute the gradients
loss.backward()

In [14]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.9901, -0.3247, -0.9835],
        [-0.1272,  1.0764,  0.5628]], requires_grad=True)
tensor([[-20249.2891, -22155.0742, -13682.9482],
        [  1771.8765,   1928.5258,   1138.1682]])


## Adjust weights and biases to reduce the loss

The loss is a [quadratic function](https://en.wikipedia.org/wiki/Quadratic_function) of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. An important insight from calculus is that the gradient indicates the rate of change of the loss, i.e., the loss function's [slope](https://en.wikipedia.org/wiki/Slope) w.r.t. the weights and biases.

If a gradient element is **positive**:

* **increasing** the weight element's value slightly will **increase** the loss
* **decreasing** the weight element's value slightly will **decrease** the loss

![postive-gradient](https://i.imgur.com/WLzJ4xP.png)

If a gradient element is **negative**:

* **increasing** the weight element's value slightly will **decrease** the loss
* **decreasing** the weight element's value slightly will **increase** the loss

![negative=gradient](https://i.imgur.com/dvG2fxU.png)

The increase or decrease in the loss by changing a weight element is proportional to the gradient of the loss w.r.t. that element. This observation forms the basis of _the gradient descent_ optimization algorithm that we'll use to improve our model (by _descending_ along the _gradient_).

We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.

In [15]:
print(w)
w.grad

tensor([[-0.9901, -0.3247, -0.9835],
        [-0.1272,  1.0764,  0.5628]], requires_grad=True)


tensor([[-20249.2891, -22155.0742, -13682.9482],
        [  1771.8765,   1928.5258,   1138.1682]])

In [16]:
with torch.no_grad(): # we use no_grad to tell torch to not incude this in the calculation of the derivative
  w -= w.grad * 1e-5#learning rate
  b -= b.grad * 1e-5

In [17]:
w,b

(tensor([[-0.7876, -0.1031, -0.8467],
         [-0.1450,  1.0571,  0.5514]], requires_grad=True),
 tensor([-0.7364,  0.7782], requires_grad=True))

We multiply the gradients with a very small number (`10^-5` in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the *learning rate* of the algorithm.

We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [18]:
# Caclulating the loss again with new predictions
loss = mse(model(inputs),targets)
print(loss)

tensor(20740.7500, grad_fn=<DivBackward0>)


Before we proceed, we reset the gradients to zero by invoking the `.zero_()` method. We need to do this because PyTorch accumulates gradients. Otherwise, the next time we invoke `.backward` on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

In [19]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Train the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can _train_ the model using the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [20]:
# Generate prediction
preds = model(inputs)
preds

tensor([[-101.5475,   84.7365],
        [-135.6705,  115.9074],
        [-132.1834,  161.8072],
        [-116.8321,   51.8527],
        [-124.2491,  130.8623]], grad_fn=<AddBackward0>)

In [21]:
# Caulate loss
loss = mse(preds,targets)
loss

tensor(20740.7500, grad_fn=<DivBackward0>)

In [22]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-16582.4004, -18213.3906, -11250.8633],
        [  1454.4067,   1587.3602,    927.6935]])
tensor([-198.2965,   17.0332])


# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

In [23]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [24]:
print(w)
print(b)

tensor([[-0.6218,  0.0790, -0.7342],
        [-0.1595,  1.0413,  0.5422]], requires_grad=True)
tensor([-0.7344,  0.7780], requires_grad=True)


With the new weights and biases, the model should have a lower loss.

In [25]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(14014.0576, grad_fn=<DivBackward0>)


## Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an _epoch_. Let's train the model for 100 epochs.

In [26]:
# Train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [27]:
# Caulate the loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(62.2188, grad_fn=<DivBackward0>)


## Linear regression using PyTorch built-ins

We've implemented linear regression & gradient descent model using some basic tensor operations. However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the `torch.nn` package from PyTorch, which contains utility classes for building neural networks.

In [28]:
import torch.nn as nn

In [29]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

## Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [30]:
from torch.utils.data import TensorDataset

In [31]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [32]:
from torch.utils.data.dataloader import DataLoader

In [33]:
# define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a `for` loop. Let's look at an example.

In [34]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [ 73.,  66.,  44.],
        [ 68.,  96.,  71.],
        [ 68.,  97.,  70.],
        [ 88., 134.,  59.]])
tensor([[119., 133.],
        [ 57.,  69.],
        [104., 118.],
        [102., 120.],
        [118., 132.]])


In each iteration, the data loader returns one batch of data with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

## nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [35]:
# Define model
model = nn.Linear(3,2) # number of columns of inputs and outputs
print(model.weight) #Randomly generating the weights and biases
print(model.bias)

Parameter containing:
tensor([[-0.2504,  0.4073, -0.4702],
        [ 0.3332, -0.4445, -0.5159]], requires_grad=True)
Parameter containing:
tensor([-0.3383, -0.5190], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [36]:
# Params
list(model.parameters())

[Parameter containing:
 tensor([[-0.2504,  0.4073, -0.4702],
         [ 0.3332, -0.4445, -0.5159]], requires_grad=True),
 Parameter containing:
 tensor([-0.3383, -0.5190], requires_grad=True)]

In [37]:
# generate predictions
preds = model(inputs)
preds

tensor([[-11.5484, -28.1583],
        [-17.3766, -42.3284],
        [  5.1813, -61.0127],
        [-25.7646,  -4.7318],
        [-11.4299, -56.3106],
        [-12.2061, -27.3806],
        [-18.2540, -42.3998],
        [  4.4607, -61.1954],
        [-25.1069,  -5.5095],
        [-11.6496, -57.1597],
        [-12.4259, -28.2297],
        [-18.0343, -41.5507],
        [  6.0587, -60.9413],
        [-25.5449,  -3.8827],
        [-10.7722, -57.0883]], grad_fn=<AddmmBackward0>)

## Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [38]:
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities.

In [39]:
loss_fn = F.mse_loss

In [40]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(14283.1982, grad_fn=<MseLossBackward0>)


## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent". The term _stochastic_ indicates that samples are selected in random batches instead of as a single group.

In [41]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(),lr=0.00001)

Note that `model.parameters()` is passed as an argument to `optim.SGD` so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified.

## Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epochs.

In [42]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [43]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 596.9666
Epoch [20/100], Loss: 594.5939
Epoch [30/100], Loss: 405.8297
Epoch [40/100], Loss: 198.9917
Epoch [50/100], Loss: 259.5618
Epoch [60/100], Loss: 126.4215
Epoch [70/100], Loss: 103.0686
Epoch [80/100], Loss: 157.5579
Epoch [90/100], Loss: 72.1903
Epoch [100/100], Loss: 35.5602


In [44]:
# Generate the predictions
preds = model(inputs)
preds

tensor([[ 57.8729,  72.2886],
        [ 77.5921,  96.7484],
        [126.1470, 137.5916],
        [ 26.5177,  49.3685],
        [ 90.7915, 105.0842],
        [ 56.6247,  71.3873],
        [ 76.6109,  96.0587],
        [126.0107, 137.8395],
        [ 27.7659,  50.2698],
        [ 91.0584, 105.2959],
        [ 56.8916,  71.5990],
        [ 76.3439,  95.8471],
        [127.1282, 138.2813],
        [ 26.2508,  49.1568],
        [ 92.0396, 105.9855]], grad_fn=<AddmmBackward0>)

In [45]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

## Machine Learning vs. Classical Programming

The approach we've taken in this tutorial is very different from programming as you might know it. Usually, we write programs that take some inputs, perform some operations, and return a result.

However, in this notebook, we've defined a "model" that assumes a specific relationship between the inputs and the outputs, expressed using some unknown parameters (weights & biases). We then show the model some know inputs and outputs and _train_ the model to come up with good values for the unknown parameters. Once trained, the model can be used to compute the outputs for new inputs.

This paradigm of programming is known as _machine learning_, where we use data to figure out the relationship between inputs and outputs. _Deep learning_ is a branch of machine learning that uses matrix operations, non-linear activation functions and gradient descent to build and train models. Andrej Karpathy, the director of AI at Tesla Motors, has written a great blog post on this topics, titled [Software 2.0](https://medium.com/@karpathy/software-2-0-a64152b37c35).

This picture from book [Deep Learning with Python](https://www.manning.com/books/deep-learning-with-python) by Francois Chollet captures the difference between classical programming and machine learning:

![](https://i.imgur.com/oJEQe7k.png)

Keep this picture in mind as you work through the next few tutorials.
